import asyncio
from decimal import Decimal
from datetime import datetime

from sqlalchemy import select, func
from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker

from app.core.config import settings
from app.models.product import Product


PRODUCTS = [
    # Electronics
    {
        "name": "iPhone 15 Pro",
        "description": "Latest iPhone with titanium design, A17 Pro chip, 48MP camera system, and USB-C connectivity.",
        "price": Decimal("999.99"),
        "image": "https://picsum.photos/seed/iphone15pro/400/400",
        "category": "Electronics",
        "brand": "Apple",
        "rating": 4.8,
        "stock": 50,
    },
    {
        "name": "Samsung Galaxy S24 Ultra",
        "description": "Premium Android flagship with built-in S Pen, 200MP camera, and AI-powered features.",
        "price": Decimal("1199.99"),
        "image": "https://picsum.photos/seed/galaxys24/400/400",
        "category": "Electronics",
        "brand": "Samsung",
        "rating": 4.7,
        "stock": 35,
    },
    {
        "name": "MacBook Pro 14-inch M3",
        "description": "Professional laptop with Apple M3 chip, Liquid Retina XDR display, and up to 22h battery.",
        "price": Decimal("1999.99"),
        "image": "https://picsum.photos/seed/macbookpro/400/400",
        "category": "Electronics",
        "brand": "Apple",
        "rating": 4.9,
        "stock": 20,
    },
    {
        "name": "Dell XPS 15",
        "description": "High-performance Windows laptop with Intel Core i9, NVIDIA RTX 4070, and 4K OLED display.",
        "price": Decimal("1799.99"),
        "image": "https://picsum.photos/seed/dellxps15/400/400",
        "category": "Electronics",
        "brand": "Dell",
        "rating": 4.6,
        "stock": 25,
    },
    {
        "name": "iPad Air M2",
        "description": "Thin and light iPad with M2 chip, 11-inch Liquid Retina display, and Apple Pencil support.",
        "price": Decimal("599.99"),
        "image": "https://picsum.photos/seed/ipadair/400/400",
        "category": "Electronics",
        "brand": "Apple",
        "rating": 4.7,
        "stock": 40,
    },
    {
        "name": "Sony WH-1000XM5",
        "description": "Industry-leading noise cancelling headphones with 30-hour battery and crystal-clear calls.",
        "price": Decimal("349.99"),
        "image": "https://picsum.photos/seed/sonywh1000/400/400",
        "category": "Electronics",
        "brand": "Sony",
        "rating": 4.8,
        "stock": 60,
    },
    {
        "name": "AirPods Pro 2nd Gen",
        "description": "Active noise cancellation, Adaptive Audio, and Personalized Spatial Audio with dynamic head tracking.",
        "price": Decimal("249.99"),
        "image": "https://picsum.photos/seed/airpodspro/400/400",
        "category": "Electronics",
        "brand": "Apple",
        "rating": 4.7,
        "stock": 80,
    },
    {
        "name": "Samsung 55\" 4K QLED TV",
        "description": "Quantum Dot technology, Neo QLED 4K, 120Hz refresh rate, and built-in smart TV features.",
        "price": Decimal("799.99"),
        "image": "https://picsum.photos/seed/samsungtv55/400/400",
        "category": "Electronics",
        "brand": "Samsung",
        "rating": 4.5,
        "stock": 20,
    },
    {
        "name": "Logitech MX Master 3S",
        "description": "Advanced wireless mouse with ultra-fast MagSpeed scrolling, 8K DPI sensor, and ergonomic design.",
        "price": Decimal("99.99"),
        "image": "https://picsum.photos/seed/mxmaster3/400/400",
        "category": "Electronics",
        "brand": "Logitech",
        "rating": 4.8,
        "stock": 100,
    },
    {
        "name": "Canon EOS R6 Mark II",
        "description": "Full-frame mirrorless camera with 40fps burst shooting, 6K RAW video, and advanced AI autofocus.",
        "price": Decimal("2499.99"),
        "image": "https://picsum.photos/seed/canoneosr6/400/400",
        "category": "Electronics",
        "brand": "Canon",
        "rating": 4.9,
        "stock": 12,
    },
    # Clothing
    {
        "name": "Levi's 501 Original Jeans",
        "description": "The original straight-fit jean with button fly. Made with sustainable cotton.",
        "price": Decimal("79.99"),
        "image": "https://picsum.photos/seed/levis501/400/400",
        "category": "Clothing",
        "brand": "Levi's",
        "rating": 4.5,
        "stock": 200,
    },
    {
        "name": "Nike Air Force 1 '07",
        "description": "Classic low-top sneaker with leather upper, Air-Sole unit, and durable rubber outsole.",
        "price": Decimal("109.99"),
        "image": "https://picsum.photos/seed/nikeaf1/400/400",
        "category": "Clothing",
        "brand": "Nike",
        "rating": 4.7,
        "stock": 150,
    },
    {
        "name": "Adidas Essential Hoodie",
        "description": "Comfortable cotton-blend hoodie with kangaroo pocket and adjustable drawcord hood.",
        "price": Decimal("64.99"),
        "image": "https://picsum.photos/seed/adidashoodie/400/400",
        "category": "Clothing",
        "brand": "Adidas",
        "rating": 4.4,
        "stock": 180,
    },
    {
        "name": "Zara Linen Summer Dress",
        "description": "Flowy midi dress in 100% linen with V-neck and side pockets. Perfect for summer.",
        "price": Decimal("49.99"),
        "image": "https://picsum.photos/seed/zaradress/400/400",
        "category": "Clothing",
        "brand": "Zara",
        "rating": 4.3,
        "stock": 120,
    },
    {
        "name": "The North Face Thermoball Jacket",
        "description": "Lightweight, packable insulated jacket that provides warmth even when wet.",
        "price": Decimal("219.99"),
        "image": "https://picsum.photos/seed/northfacejacket/400/400",
        "category": "Clothing",
        "brand": "The North Face",
        "rating": 4.8,
        "stock": 75,
    },
    {
        "name": "Uniqlo AIRism Polo Shirt",
        "description": "Breathable performance polo with moisture-wicking AIRism fabric and UV protection.",
        "price": Decimal("39.99"),
        "image": "https://picsum.photos/seed/uniqlopolo/400/400",
        "category": "Clothing",
        "brand": "Uniqlo",
        "rating": 4.5,
        "stock": 300,
    },
    {
        "name": "H&M Basic T-Shirt",
        "description": "100% organic cotton classic-fit t-shirt available in multiple colors.",
        "price": Decimal("14.99"),
        "image": "https://picsum.photos/seed/hmtshirt/400/400",
        "category": "Clothing",
        "brand": "H&M",
        "rating": 4.1,
        "stock": 500,
    },
    {
        "name": "Puma Running Shorts",
        "description": "Lightweight 5-inch inseam running shorts with inner liner and reflective elements.",
        "price": Decimal("34.99"),
        "image": "https://picsum.photos/seed/pumashorts/400/400",
        "category": "Clothing",
        "brand": "Puma",
        "rating": 4.2,
        "stock": 250,
    },
    # Books
    {
        "name": "Clean Code",
        "description": "A handbook of agile software craftsmanship by Robert C. Martin. Essential reading for developers.",
        "price": Decimal("39.99"),
        "image": "https://picsum.photos/seed/cleancode/400/400",
        "category": "Books",
        "brand": "Prentice Hall",
        "rating": 4.8,
        "stock": 500,
    },
    {
        "name": "The Pragmatic Programmer",
        "description": "From journeyman to master — timeless advice for software developers on their craft.",
        "price": Decimal("44.99"),
        "image": "https://picsum.photos/seed/pragprog/400/400",
        "category": "Books",
        "brand": "Addison-Wesley",
        "rating": 4.9,
        "stock": 400,
    },
    {
        "name": "Designing Data-Intensive Applications",
        "description": "Deep dive into the internals of modern databases, streaming systems, and distributed systems.",
        "price": Decimal("54.99"),
        "image": "https://picsum.photos/seed/ddia/400/400",
        "category": "Books",
        "brand": "O'Reilly",
        "rating": 4.9,
        "stock": 350,
    },
    {
        "name": "Python Crash Course",
        "description": "A hands-on, project-based introduction to Python programming for beginners and intermediates.",
        "price": Decimal("35.99"),
        "image": "https://picsum.photos/seed/pythoncrash/400/400",
        "category": "Books",
        "brand": "No Starch Press",
        "rating": 4.7,
        "stock": 700,
    },
    {
        "name": "Atomic Habits",
        "description": "An easy and proven way to build good habits and break bad ones by James Clear.",
        "price": Decimal("16.99"),
        "image": "https://picsum.photos/seed/atomichabits/400/400",
        "category": "Books",
        "brand": "Avery",
        "rating": 4.8,
        "stock": 1000,
    },
    {
        "name": "Dune",
        "description": "Epic science fiction novel by Frank Herbert set in the distant future amidst a feudal interstellar society.",
        "price": Decimal("14.99"),
        "image": "https://picsum.photos/seed/dunebook/400/400",
        "category": "Books",
        "brand": "Ace Books",
        "rating": 4.8,
        "stock": 900,
    },
    {
        "name": "JavaScript: The Good Parts",
        "description": "Unearthing the excellence in JavaScript by Douglas Crockford. A must-read for JS developers.",
        "price": Decimal("29.99"),
        "image": "https://picsum.photos/seed/jsgoodparts/400/400",
        "category": "Books",
        "brand": "O'Reilly",
        "rating": 4.5,
        "stock": 600,
    },
    {
        "name": "System Design Interview",
        "description": "An insider's guide to system design interviews, covering scalability, reliability, and performance.",
        "price": Decimal("49.99"),
        "image": "https://picsum.photos/seed/systemdesign/400/400",
        "category": "Books",
        "brand": "Independently Published",
        "rating": 4.6,
        "stock": 800,
    },
    # Home
    {
        "name": "Dyson V15 Detect Vacuum",
        "description": "Powerful cordless vacuum with laser dust detection, HEPA filtration, and 60-min runtime.",
        "price": Decimal("699.99"),
        "image": "https://picsum.photos/seed/dysonv15/400/400",
        "category": "Home",
        "brand": "Dyson",
        "rating": 4.8,
        "stock": 25,
    },
    {
        "name": "Instant Pot Duo 7-in-1",
        "description": "Electric pressure cooker that replaces 7 kitchen appliances. 8-quart capacity.",
        "price": Decimal("89.99"),
        "image": "https://picsum.photos/seed/instantpot/400/400",
        "category": "Home",
        "brand": "Instant Pot",
        "rating": 4.7,
        "stock": 100,
    },
    {
        "name": "Nespresso Vertuo Next",
        "description": "Coffee machine with Centrifusion technology for perfect espresso and coffee at home.",
        "price": Decimal("179.99"),
        "image": "https://picsum.photos/seed/nespresso/400/400",
        "category": "Home",
        "brand": "Nespresso",
        "rating": 4.6,
        "stock": 60,
    },
    {
        "name": "Philips Air Purifier 3000i",
        "description": "Smart air purifier with HEPA filtration, removes 99.97% of allergens and ultrafine particles.",
        "price": Decimal("299.99"),
        "image": "https://picsum.photos/seed/philipsair/400/400",
        "category": "Home",
        "brand": "Philips",
        "rating": 4.5,
        "stock": 40,
    },
    {
        "name": "KitchenAid Artisan Stand Mixer",
        "description": "Iconic 5-quart tilt-head stand mixer with 10 speeds and over 80 compatible attachments.",
        "price": Decimal("499.99"),
        "image": "https://picsum.photos/seed/kitchenaid/400/400",
        "category": "Home",
        "brand": "KitchenAid",
        "rating": 4.9,
        "stock": 20,
    },
    {
        "name": "IKEA KALLAX Shelf Unit",
        "description": "Versatile shelf unit that works as room divider, TV bench, or bookcase. 4x4 cubbies.",
        "price": Decimal("149.99"),
        "image": "https://picsum.photos/seed/ikeakallax/400/400",
        "category": "Home",
        "brand": "IKEA",
        "rating": 4.3,
        "stock": 50,
    },
    {
        "name": "Cuisinart Smart Stick Blender",
        "description": "200-watt hand blender with stainless steel blending shaft and detachable design.",
        "price": Decimal("49.99"),
        "image": "https://picsum.photos/seed/cuisinart/400/400",
        "category": "Home",
        "brand": "Cuisinart",
        "rating": 4.4,
        "stock": 80,
    },
    {
        "name": "Bamboo Cutting Board Set",
        "description": "Set of 3 premium bamboo cutting boards in different sizes with juice groove and handles.",
        "price": Decimal("34.99"),
        "image": "https://picsum.photos/seed/bamboocutting/400/400",
        "category": "Home",
        "brand": "Royal Craft Wood",
        "rating": 4.6,
        "stock": 200,
    },
    # Sport
    {
        "name": "Nike React Infinity Run 3",
        "description": "Running shoe designed to help reduce injury with extra foam cushioning and wide base.",
        "price": Decimal("159.99"),
        "image": "https://picsum.photos/seed/nikereact/400/400",
        "category": "Sport",
        "brand": "Nike",
        "rating": 4.6,
        "stock": 100,
    },
    {
        "name": "Garmin Forerunner 265",
        "description": "GPS running smartwatch with AMOLED display, training readiness, and race predictor.",
        "price": Decimal("449.99"),
        "image": "https://picsum.photos/seed/garminforerunner/400/400",
        "category": "Sport",
        "brand": "Garmin",
        "rating": 4.7,
        "stock": 45,
    },
    {
        "name": "Manduka PRO Yoga Mat",
        "description": "6mm thick performance yoga mat with closed-cell surface for superior grip and hygiene.",
        "price": Decimal("120.00"),
        "image": "https://picsum.photos/seed/mandukayoga/400/400",
        "category": "Sport",
        "brand": "Manduka",
        "rating": 4.8,
        "stock": 150,
    },
    {
        "name": "TRX All-In-One Suspension Trainer",
        "description": "Professional-grade suspension trainer for full-body workouts anywhere, indoors or outdoors.",
        "price": Decimal("189.99"),
        "image": "https://picsum.photos/seed/trxsuspension/400/400",
        "category": "Sport",
        "brand": "TRX",
        "rating": 4.7,
        "stock": 80,
    },
    {
        "name": "Fitbit Charge 6",
        "description": "Advanced fitness tracker with Google integration, heart rate monitoring, and GPS.",
        "price": Decimal("159.99"),
        "image": "https://picsum.photos/seed/fitbitcharge/400/400",
        "category": "Sport",
        "brand": "Fitbit",
        "rating": 4.5,
        "stock": 90,
    },
    {
        "name": "Resistance Bands Set (11 pcs)",
        "description": "Set of 11 resistance bands from 10 to 150 lbs for strength training and rehabilitation.",
        "price": Decimal("29.99"),
        "image": "https://picsum.photos/seed/resistancebands/400/400",
        "category": "Sport",
        "brand": "Fit Simplify",
        "rating": 4.5,
        "stock": 300,
    },
    # Beauty
    {
        "name": "Dyson Airwrap Complete",
        "description": "Multi-styler that styles and dries simultaneously using Coanda airflow effect.",
        "price": Decimal("599.99"),
        "image": "https://picsum.photos/seed/dysonairwrap/400/400",
        "category": "Beauty",
        "brand": "Dyson",
        "rating": 4.7,
        "stock": 30,
    },
    {
        "name": "La Mer Crème de la Mer",
        "description": "Legendary moisturizing cream with sea kelp, calcium, vitamins and minerals.",
        "price": Decimal("395.00"),
        "image": "https://picsum.photos/seed/lamer/400/400",
        "category": "Beauty",
        "brand": "La Mer",
        "rating": 4.6,
        "stock": 50,
    },
    {
        "name": "Fenty Beauty Pro Filt'r Foundation",
        "description": "Soft matte longwear foundation available in 50 shades for all skin tones.",
        "price": Decimal("38.00"),
        "image": "https://picsum.photos/seed/fenty/400/400",
        "category": "Beauty",
        "brand": "Fenty Beauty",
        "rating": 4.5,
        "stock": 200,
    },
    {
        "name": "CeraVe Hydrating Facial Cleanser",
        "description": "Gentle, hydrating face wash with ceramides and hyaluronic acid for normal to dry skin.",
        "price": Decimal("14.99"),
        "image": "https://picsum.photos/seed/cerave/400/400",
        "category": "Beauty",
        "brand": "CeraVe",
        "rating": 4.8,
        "stock": 500,
    },
    {
        "name": "Charlotte Tilbury Pillow Talk Lipstick",
        "description": "Iconic universally flattering nude-pink lipstick in a matte or satin finish.",
        "price": Decimal("34.00"),
        "image": "https://picsum.photos/seed/charlottes/400/400",
        "category": "Beauty",
        "brand": "Charlotte Tilbury",
        "rating": 4.7,
        "stock": 300,
    },
    {
        "name": "The Ordinary Retinol 1% Serum",
        "description": "High-strength retinol in squalane to target signs of aging and refine skin texture.",
        "price": Decimal("9.99"),
        "image": "https://picsum.photos/seed/theordinary/400/400",
        "category": "Beauty",
        "brand": "The Ordinary",
        "rating": 4.5,
        "stock": 600,
    },
]


async def seed() -> None:
    engine = create_async_engine(settings.DATABASE_URL, echo=False)
    session_factory = async_sessionmaker(engine, expire_on_commit=False)

    async with session_factory() as session:
        count = await session.scalar(select(func.count()).select_from(Product))
        if count and count > 0:
            print(f"Database already has {count} products. Skipping seed.")
            await engine.dispose()
            return

        now = datetime.utcnow()
        for data in PRODUCTS:
            session.add(Product(**data, created_at=now, updated_at=now))

        await session.commit()
        print(f"Seeded {len(PRODUCTS)} products successfully.")

    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(seed())
